editor/src/main/java/io/github/rosemoe/editor/text/Cursor.java
editor/src/main/java/io/github/rosemoe/editor/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/editor/widget/EditorTouchEventHandler.java
editor/src/main/java/io/github/rosemoe/editor/widget/SymbolPairMatch.java
language-java/src/main/java/io/github/rosemoe/editor/langs/java/JavaLanguage.java

If the whole text is selected, clicking on a whitespace in the selected region exits selection mode.
* It's related to #46 (as mentioned in [this](https://github.com/Rosemoe/CodeEditor/issues/46#issuecomment-815457838)  comment.)
* JavaLanguage now returns ```DefaultSymbolPairs``` in ```JavaLanguage#getSymbolPairs()``` (#48)
* Added some common symbol pairs in ```CodeEditor#getOverrideSymbolPairs()``` (#44)

If the whole text is selected, clicking on a whitespace in the selected region exits selection mode

---

editor/src/main/java/io/github/rosemoe/editor/widget/EditorAutoCompleteWindow.java

Fix ClassCastException in EditorAutoCompleteWindow when selecting an item from the completion list. This happens only when an adapter other than the ```DefaultCompletionListAdapter``` is set.

Fix ClassClassException in EditorAutoCompleteWindow

---

editor/src/main/java/io/github/rosemoe/editor/text/FontCache.java

Fix syntax error in isEmoji method caused by last modification(修复上次修改引起的isEmoji方法中的语法错误)非常抱歉_(:з」∠)_

Fix syntax error  caused by last modification

---

build.gradle
editor/src/main/java/io/github/rosemoe/editor/widget/EditorTouchEventHandler.java

As mentioned in [this](https://github.com/Rosemoe/CodeEditor/issues/46#issuecomment-815457838) comment. It was fixed in #49 but wasn't working for [TextActionPopupWindow](https://github.com/Rosemoe/CodeEditor/blob/main/editor/src/main/java/io/github/rosemoe/editor/widget/TextActionPopupWindow.java)

Fix #46 for TextActionPopupWindow

---

app/build.gradle
app/src/main/java/io/github/rosemoe/editor/app/MainActivity.java
language-html/src/main/java/io/github/rosemoe/editor/langs/html/HTMLAutoComplete.java
language-html/src/main/java/io/github/rosemoe/editor/langs/html/HTMLLanguage.java

- Fixed: HTML tags were being added again to the completion list instead of HTML attributes.
- Added: Append closing tag along with the opening tag.

Added auto-close HTML tags in HTMLAutoComplete

---

editor/src/main/java/io/github/rosemoe/editor/widget/CodeEditor.java

When the device is in landscape mode, the soft keyboard acquires most of the screen height. The IME then forces the editor to go fullscreen.

- Added option to disable fullscreen in landscape mode

---

editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java

I found this to be useful when I wanted to customize the TextActionPopupWindow to edit **More** button, but it can be used to create custom popup windows as well.
Also made getTextActionPresenter() public for completeness.

Add setTextActionPresenter() to set custom EditorTextActionPresenters

---

editor/src/main/java/io/github/rosemoe/sora/lang/completion/CompletionPublisher.java
editor/src/main/java/io/github/rosemoe/sora/widget/component/EditorAutoCompletion.java
editor/src/main/java/io/github/rosemoe/sora/widget/component/EditorCompletionAdapter.java

The adapter was being refreshed three times when requireCompletion() is invoked.
The first refresh is with the call to `mAdapter#setValues()`, The second refresh is the call to `mAdapterView#setAdapter()` and the third refresh is on the callback at CompletionPublisher.
This refreshes causes the flickering of the completion window, to solve this I made the list refresh only after the items have arrived.

Fixed flickering of completion window when invoked multiple times.

---

app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
editor/src/main/AndroidManifest.xml
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/CursorAnimator.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorPainter.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java
editor/src/main/java/io/github/rosemoe/sora/widget/FadeCursorAnimator.java
editor/src/main/java/io/github/rosemoe/sora/widget/MoveCursorAnimator.java
editor/src/main/java/io/github/rosemoe/sora/widget/ScaleCursorAnimator.java
editor/src/main/java/io/github/rosemoe/sora/widget/style/SelectionHandleStyle.java
editor/src/main/java/io/github/rosemoe/sora/widget/style/builtin/HandleStyleDrop.java
editor/src/main/java/io/github/rosemoe/sora/widget/style/builtin/HandleStyleSideDrop.java

I'm not sure if it's okay to put `setScale()` and `setAlpha()` methods in `SelectionHandleStyle`, but you got the idea
\+ Vibrate on long press just like normal EditText widget
_FadeCursorAnimator_
_ScaleCursorAnimator_

Provide different `CursorAnimator` implementations

---

editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorPainter.java

Provide support for sticky text selection as if it would be a normal EditText
_isStickyTextSelection = true_
_isStickyTextSelection = false_

Support for sticky text selection

---

language-textmate/src/main/java/io/github/rosemoe/sora/textmate/core/internal/parser/xml/XMLPListParser.java

By the way, it would be better to use XmlPullParser and Driver instead of SAX as it is more efficient and is recommended in android docs

fix XXE vulnerability in XML Parsing

---

app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
editor/src/main/java/io/github/rosemoe/sora/widget/EditorPainter.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java
editor/src/main/java/io/github/rosemoe/sora/widget/component/Magnifier.java
editor/src/main/res/layout/magnifier_popup.xml

Equivalent of `setAntiAlias(true)` or `setFilterBitmap(true)`
Before:
After:
When using sticky selection, it will follow the cursor position if the distance between cursor and motion event more than a height of 1 char
Before:
After:

Improve magnifier

---

.idea/misc.xml
app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml
build.gradle
editor/src/main/java/io/github/rosemoe/sora/event/EditorKeyEvent.java
editor/src/main/java/io/github/rosemoe/sora/event/KeyBindingEvent.java
editor/src/main/java/io/github/rosemoe/sora/text/ICUUtils.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/DirectAccessProps.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorInputConnection.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorKeyEventHandler.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java
language-textmate/src/main/java/io/github/rosemoe/sora/textmate/core/internal/parser/xml/XMLPListParser.java

This PR adds `KeyBindingEvent` and support for handling a few more keybidings.
This event is dispatched to receivers when users press some special keys at the same time. For example, this event will be dispatched if a user presses `Ctrl + any alphabet key`.
- `Ctrl + D`: If content is selected, duplicates the selected content else duplicates the current line.
- `Ctrl + W`: Selects the word at the left selection handle.
- `Shift + Enter`: Start a new line.
- `Ctrl + Enter`: Split line. If content is selected, deletes the selected content then splits the line.
- `Ctrl + Alt + Enter` : Start a new line before current line.
- `Ctrl + Shift + J`: Join current line and next line.
- `Ctrl + X`: If no content is selected, cuts the current line. Else, performs the usual cut operation.
- `Ctrl + …

Added KeyBIndingEvent and support for more keybindings

---

app/src/main/java/io/github/rosemoe/sora/app/LspTestActivity.kt
editor-lsp/README.md
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/DefaultLanguageClient.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/languageserver/requestmanager/DefaultRequestManager.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/languageserver/wrapper/LanguageServerWrapper.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/LspEditor.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/LspEditorManager.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/LspLanguage.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/completion/CompletionItemProvider.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/completion/LspCompletionItem.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/event/LspEditorContentChangeEventReceiver.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/format/LspFormatter.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/Feature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/diagnostics/PublishDiagnosticsFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/document/ApplyEditsFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/document/DocumentChangeFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/document/DocumentCloseFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/document/DocumentOpenFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/document/DocumentSaveFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/format/FullFormattingFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/operations/format/RangeFormattingFeature.java
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/utils/LspUtils.java

Add code snippet support in code completion for `editor-lsp`. 
like this :
But it is not full code snippet support, because the editor does not yet provide support for code snippets.
So currently it only supports simple code snippets with Tabstops, the editor cursor will be moved to the first Tabstops position, other syntax (e.g. Choice, Placeholder, etc.) is not supported and will be replaced with empty string.
For the syntax of the code snippet, see [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets).

Add code snippet support in code completion for `editor-lsp`

---

editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java

This PR fixes a bug which causes `StackOverflowError` in the `CodeEditor.copyLine()` method.
An external keyboard or Hackers Keyboard is required to reproduce this.
Steps :
- Place the cursor on an empty line (not a blank line!).
- Press the `Ctrl + C` keybinding.

Fixed StackOverflowError in CodeEditor.copyLine()

---

language-textmate/build.gradle.kts

In the new textmate update, these xml classes are no longer used. Proposing this PR as this dependency causes conflicts with the org.w3c.dom.html.HTMLDOMImplementation that our Ide already includes with the JAXP bundle

Remove xerces dependency

---

app/src/main/assets/textmate/darcula.json
language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/TextMateColorScheme.java

Now you can set custom bracket foreground color when it is selected by modifying the color scheme. It is useful when you have a dark background for editor and want the bracket foreground to be something lighter

feature: custom bracket background by theme

---

README.md
app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
editor/src/main/java/io/github/rosemoe/sora/text/CharPosition.java
editor/src/main/java/io/github/rosemoe/sora/util/Chars.kt
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorKeyEventHandler.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java
keybindings.md

This PR adds support for the following keybindings :
- `Ctrl+Left` : Move to word start. If the cursor is already at the current word's start, moves the cursor to previous word's start, skipping whitespaces.
- `Ctrl+Right` : Move to word end. If the cursor is already at the current word's end, moves the cursor to next word's end, skipping whitespaces.
- `Ctrl+Up` : Scroll up by one row.
- `Ctrl+Down` : Scroll down by one row.
- `Ctrl+Shift+Left` : Same as `Ctrl+Left`, but starts or updates the selection.
- `Ctrl+Shift+Right` : Same as `Ctrl+Right`, but starts or updates the selection.
- `Ctrl+Shift+Up` : Moves the current line (or all selected lines) up by one line.
- `Ctrl+Shift+Down` : Moves the current line (or all selected lines) down by one line.
- `Ctrl+Home` : Moves the cursor to …

Added more keybindings

---

.idea/compiler.xml
.idea/misc.xml
editor/src/main/java/io/github/rosemoe/sora/event/EditorKeyEvent.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/component/EditorAutoCompletion.java

This PR fixes the following issues : 
- As stated in AndroidIDEOfficial/AndroidIDE#562, the editor currently does not make use of `Language.useTab()` when `KEYCODE_TAB` key event is received from the IME. Instead, it has the tab character hardcoded in it.
- Currently, it is not possible to intercept key events in editor because both, `EditorKeyEvent` and `KeyBindingEvent` does not implement the `canIntercept()` method.

Removed hardcoded '\t' in CodeEditor.commitTab() and made EditorKeyEvent interceptable

---

editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/DirectAccessProps.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java
language-textmate/src/main/java/org/eclipse/tm4e/core/internal/oniguruma/OnigRegExp.java

1. 当有多个 editor 实例时 OnigRegExp 类里面的缓存会被多线程访问，会导致崩溃 
2. 如果当前已经选中了文字显示了TextAction，再长按别处，可以切换选中。
3. requestFocusFromTouch 会导致 弹出的 TextAction 不符合预期的获取到焦点，按钮是选中状态；设置selection 时自动获取焦点。

fix multi thread error in OnigRegExp, etc

---

language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/TextMateNewlineHandler.java

See error log:
```
Crash at 1672804988527(timestamp) in thread named 'main'
Local date and time:2023年1月4日 12:03:08
BOARD=oppo6765_19181
ACTIVE_CODENAMES=[]
CPU_ABI2=
HOST=Ubuntu-134-12
versionName=0.20.1-1671792647944
SUPPORTED_64_BIT_ABIS=[arm64-v8a]
CODENAME=REL
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=false
SDK_INT=28
DISPLAY=PDBM00_11_A.30
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
FINGERPRINT=OPPO/PDBM00/OP4AED:9/PPR1.180610.011/1641904128:user/release-keys
PRODUCT=PDBM00
ID=PPR1.180610.011
SDK=28
TYPE=user
SERIAL=unknown
DEVICE=OP4AED
RESOURCES_SDK_INT=28
SECURITY_PATCH=2022-01-05
TIME=1641910166000
BASE_OS=OPPO/PDBM00/OP4AED:9/PPR1.180610.011/1636948094:user/release-keys
MODEL=PDBM00
RELEASE=9
MANUFACTURER=OPPO
USER=root
versionCode=72
BRAND=OPPO …
```

fix: An exception on TextMateNewlineHandler

---

editor/src/main/java/io/github/rosemoe/sora/event/EventManager.java

Simply detect if the event receiver has been added and return the SubscriptionReceipt directly.
Even if add multiple subscription, actually send an event, the event receiver will only receive an event once.
See also how [LiveData does](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-livedata-core/src/main/java/androidx/lifecycle/LiveData.java;l=190;drc=b69fe340ccf37160705e6d7dc512b814fd6bb100) it.

feat: the same receiver in the EventManager can subscribe to the same event type multiple times

---

gradle/libs.versions.toml

The group id for [`android-tree-sitter`](https://github.com/AndroidIDEOfficial/android-tree-sitter) was recently changed from `io.github.itsaky` to `com.itsaky.androidide`.
The change of Maven group from `io.github.itsaky` to `com.itsaky.androidide` for the `android-tree-sitter` repository was made to align it with the AndroidIDE project, which has the **same package name**. This change will help to organize the project more effectively and make it easier for us to locate and use the repository. By using a consistent naming convention across all modules of the AndroidIDE project, it will be simpler for us to maintain and update the codebase in the future.

Update Maven group ID and version for android-tree-sitter

---

gradle/libs.versions.toml
language-textmate/build.gradle.kts

Fixes issues with old APIs (Android < 8).
Closes #416

Upgrade desugar_jdk_libs to 2.0.3

---

editor/src/main/java/io/github/rosemoe/sora/lang/styling/CodeBlock.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorRenderer.java

The `binarySearchEndBlock` method now handles cases where a `null` `CodeBlock` is encountered during the search. The code now adjusts the indices to continue the search until a non-null `CodeBlock` is found. This fix prevents `NullPointerException` when accessing null `CodeBlock`s in the list.
Also, the method now returns -1 if no block is found.
This change should fix AndroidIDEOfficial/AndroidIDE#927 and hopefully AndroidIDEOfficial/AndroidIDE#906.

fix: handle null CodeBlock in binarySearchEndBlock

---

gradle/libs.versions.toml
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsAnalyzeManager.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsBracketPairs.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsLanguageSpec.kt

This PR addresses the breaking change introduced in [android-tree-sitter v3.0.0](https://github.com/AndroidIDEOfficial/android-tree-sitter/releases/tag/v3.0.0).

fix: migrate to android-tree-sitter v3.0.0

---

language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/TextMateColorScheme.java

You can now apply the completion item background when using `TextMateColorScheme` by modifying the textmate theme.
Example
```json
{
"name": "darcula",
"settings": [
{
"settings": {
"completionWindowBackground": "#1F1A1B",
"completionWindowBackgroundCurrent": "#1F1A1B"
}
}
]
}
```

Support for applying completion item background with textmate color schemes

---

app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
app/src/main/java/io/github/rosemoe/sora/lang/langJava.kt
editor/src/main/java/io/github/rosemoe/sora/lang/styling/color/ResolvableColor.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/LineSpansGenerator.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsAnalyzeManager.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsLanguage.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/spans/DefaultSpanFactory.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/spans/TsSpanFactory.kt

This PR adds a new API that allows `TsAnalyzeManager` implementations to create custom `Span`s and styles for the captures.
`TsAnalyzeManager` implementations can provide a `TsSpanFactory` instance which is used to create the spans (and styles for the capture). The span factory is provided with the `TSQueryCapture` object representing the query capture along with the column index and styles for the `Span`.
The default implementation of the factory (`DefaultTsSpanFactory`) simply creates the spans using `Span.obtain`.
As an example, the tree-sitter based Java language in the sample application uses a custom span factory to add a `LineGutterBackground` anchor style to lines which contain a HEX color string.

feat(lang-ts): add API for creating custom Spans in tree sitter languages

---

app/src/main/assets/samples/sample.txt
editor/src/main/java/io/github/rosemoe/sora/lang/styling/Span.java
editor/src/main/java/io/github/rosemoe/sora/lang/styling/SpanPool.kt
editor/src/main/java/io/github/rosemoe/sora/lang/styling/StaticColorSpan.kt
editor/src/main/java/io/github/rosemoe/sora/util/RendererUtils.kt
editor/src/main/java/io/github/rosemoe/sora/widget/EditorRenderer.java
editor/src/main/java/io/github/rosemoe/sora/widget/schemes/EditorColorScheme.java
language-java/src/main/java/io/github/rosemoe/sora/langs/java/JavaIncrementalAnalyzeManager.java

This PR adds support for static color spans in the editor.
Static color spans are spans whose background and foreground colors are pre-defined during the source code analysis. Two new color IDs have been added to `EditorColorScheme` :
- `STATIC_SPAN_BACKGROUND` -> for the background
- `STATIC_SPAN_FOREGROUND` -> for the foreground
Here is a demo implementation of the feature (the color is same for all string tokens) :
There is only one issue that I have noticed and it is not specifically related to this feature addition :
If a span has a custom background color and if that span is in the selection region, the span background color hides the selected text background color. This happens because the selection is drawn before the span (i.e. the span color overlaps the selection color).
This …

feat(editor): add support for static span colors

---

editor/src/main/java/io/github/rosemoe/sora/text/TextUtils.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/DirectAccessProps.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorKeyEventHandler.java
editor/src/main/java/io/github/rosemoe/sora/widget/SymbolInputView.java
keybindings.md

This adds the ability to indent selected text when the `TAB` key is pressed. The feature can be enabled/disabled using [`DirectAccessProps.indentSelectionWithTab`](https://github.com/itsaky/sora-editor/blob/fe05ee150a7da1bbb62ee341fea2aea0ec7b8a18/editor/src/main/java/io/github/rosemoe/sora/widget/DirectAccessProps.java#L378).
Related issue : AndroidIDEOfficial/AndroidIDE#1229
https://github.com/Rosemoe/sora-editor/assets/46931079/26974213-e321-4195-88d7-2bb771b19e8d
https://github.com/Rosemoe/sora-editor/assets/46931079/6ab5aa87-5ad1-4dc3-b306-3a115c67559b

feat(editor): indent selected text on TAB key event

---

app/src/main/java/io/github/rosemoe/sora/lang/langJava.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/LineSpansGenerator.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/spans/DefaultSpanFactory.kt
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/spans/TsSpanFactory.kt

This PR updates the `TsSpanFactory` API so that multiple (not-overlapping) spans can be created for a single capture. This feature is useful for cases where a capture's node(s) may need to be represented with different spans.
An example implementation for this (with static color spans) has been added to the Tree Sitter Java language in the sample application. Here is a screenshot :

Add support for adding multiple spans for single capture in TsSpanFactory

---

editor/src/main/java/io/github/rosemoe/sora/widget/base/EditorPopupWindow.java

If the `PopupWindow` is dismissed by the system, the `EditorPopupWindow.dismiss()` will not be called and hence the `showState` in `EditorPopupWindow` and the actual show state of the popup window will differ.
This PR fixes the above issue by removing usage of `showState` in `EditorPopupWindow` and replacing it with `PopupWindow.isShowing()` call.

fix: replace 'showState' in EditorPopupWindow with 'PopupWindow.isShowing()'

---

editor/src/main/java/io/github/rosemoe/sora/lang/styling/Styles.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
language-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsAnalyzeManager.kt

This PR adds null checks in `CodeEditor.findCursorBlock()` and `Styles.addCodeBlock` to avoid runtime exception when querying the blocks. An issue related to this was reported in AndroidIDEOfficial/AndroidIDE#1388.

fix: add null checks for CodeBlocks

---

app/src/main/java/io/github/rosemoe/sora/app/MainActivity.kt
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml
editor/src/main/java/io/github/rosemoe/sora/util/KeyboardUtils.kt
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java

This feature add support for the following feature switches :
- To enable or disable the soft keyboard.
- To disable the soft keyboard if a hardware keyboard is available (either built-in or external).

feat: add feature switches to enable/disable soft keyboard

---

editor/src/main/java/io/github/rosemoe/sora/event/SelectionChangeEvent.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java

feat(editor): add old cursor position params before changed for selection change event

feat(editor): add old cursor position params for selection change event

---

editor/src/main/java/io/github/rosemoe/sora/lang/Language.java
editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java

Currently, the `getIndentAdvance` method in `Language` interface expects the implementations to return the number of spaces to increase or decrease relative to the current line's indentation (`newLineIndent = currLineIndent + getIndentAdvance(...)`). However, the method does not provide the indentation count on the current line, which might be problematic in some cases (for example, if the implementation computes the overall indentation, not the delta). This PR adds a new overload for `getIndentAdvance` which provides the number of spaces and tabs on the current line.

fix: provide space and tab count to Language.getIndentAdvance()

---

language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/TextMateSymbolPairMatch.java

--bugfix=TextMateSymbolPairMatch.SymbolPairEx.shouldReplace add isSurroundingPair judgement when no text was selected.

--bugfix=TextMateSymbolPairMatch.SymbolPairEx.shouldReplace

---

editor/src/main/java/io/github/rosemoe/sora/widget/SymbolPairMatch.java
language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/TextMateSymbolPairMatch.java

Fix the issue where duplicate symbols in autoClosingPairs and surrounding Pairs cannot be completed when the text is not selected

--bugfix=Fix the issue:https://github.com/Rosemoe/sora-editor/issues/602

---

editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java
editor/src/main/java/io/github/rosemoe/sora/widget/SymbolPairMatch.java

--bugfix=Fix SymbolPairMatch#matchBestPair return incorrect result

--bugfix=Fix SymbolPairMatch#matchBestPair return incorrect result

---

editor/src/main/java/io/github/rosemoe/sora/lang/completion/CompletionItem.java

I think that it should be public to be able to use custom icon on custom completion adapter depending on item's kind.
Just like CompletionItem.label or CompletionItem.desc.

Making CompletionItem.kind public

---

editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/DefaultLanguageClient.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/connection/CustomConnectProvider.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/client/languageserver/requestmanager/DefaultRequestManager.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/LspEditor.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/LspLanguage.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/completion/LspCompletionItem.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/editor/event/LspEditorContentChangeEventReceiver.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/events/EventEmitter.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/events/diagnostics/PublishDiagnosticsEvent.kt
editor-lsp/src/main/java/io/github/rosemoe/sora/lsp/events/diagnostics/QueryDocumentDiagnosticsEvent.kt

- Improve the signature help trigger logic by adding support for triggering it when the selection changes and the character at the selection's left boundary matches a specific condition.
- Adjust thread usage in LspEditor to ensure that the `sleep` operation is performed on a background thread using `Dispatchers.IO`.
- Remove the `FIXME` comment in DefaultLanguageClient, as the support for diagnostics is now implemented.
- Change the `StreamProvider` interface in CustomConnectProvider to a functional interface, simplifying its usage and improving code readability.
- Implemented diagnostic request and publishing logic within the event handling mechanism.
- Updated the request manager to support diagnostic requests.
- Adjusted event data handling for diagnostics to improve type safety and …

refactor(language-lsp): improve signature help trigger, basic diagnostics support 

---

language-textmate/build.gradle.kts

Disable desugaring on language-textmate module (Only)
while at the same time keep it on sora editor app. So that Applications using language-textmate can disable desugaring if they target only new apis.

Disable desugaring on language-textmate module (ONLY)

---

editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java

Fixes magnifier position when slowly moving the handle with sticky text selection enabled
**Before:**
https://github.com/user-attachments/assets/a4b5537c-5c82-44ba-96ca-5e7bc9575f65
**After:**
https://github.com/user-attachments/assets/01456e34-df33-4f7d-b0c6-217d82fb56e6

Fix sticky text selection magnifier

---

editor/src/main/java/io/github/rosemoe/sora/widget/EditorRenderer.java

Changes paint style from `FILL_AND_STROKE` to `FILL` if `DirectAccessProps.boldMatchingDelimiters` is true

Fix bold matching delimiters

---

editor/src/main/java/io/github/rosemoe/sora/widget/EditorRenderer.java
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java

Currently, `EditorRenderer` always rendering current line background, even if `isHighlightCurrentLine` is set to `false`

Fix current line being highlighted when property is disabled

---

editor/src/main/java/io/github/rosemoe/sora/widget/EditorRenderer.java

Fixes a bug where `enableRoundTextBackground` property didn't affect selection background for an empty line

Fix rounded corners

---

editor/src/main/java/io/github/rosemoe/sora/widget/component/DefaultCompletionLayout.java

Changed stroke width of completion window from 1px to 1dp. This is a small but noticeable difference
Before / After:

Set stroke width to 1 dp

---

editor/src/main/java/io/github/rosemoe/sora/event/ClickEvent.java
editor/src/main/java/io/github/rosemoe/sora/event/DoubleClickEvent.java
editor/src/main/java/io/github/rosemoe/sora/event/EditorMotionEvent.java
editor/src/main/java/io/github/rosemoe/sora/event/LongPressEvent.java
editor/src/main/java/io/github/rosemoe/sora/event/editorMinorEvents.kt
editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java

See #678 for more details.
---
I added static fields in `EditorMotionEvent` for regions and region bounds because I believe that the definitions should be in `EditorMotionEvent` class itself, and not within a separate `RegionResolverKt` class (library users shouldn't have to look for the possible values of `motionRegion` and `motionBound`). But since we also have to ensure backwards compatibility, the fields in `EditorMotionEvent` simply delegate to the values in `RegionResolverKt`. If you have anything else in mind for this, just let me know and I'll get it done.

fix: include motion region and motion bounds with EditorMotionEvent
